server:
  port: 8083
  
spring:  datasource:    url: jdbc:mysql://localhost:3306/stock
    username: root
    password: N0tall0wed
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:    hibernate:      ddl-auto: update
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
        
      application:    name: dashboard
    
    
      